{% set name = "cupy-xarray" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cupy-xarray-{{ version }}.tar.gz
  sha256: b6379ffdd0f22cf3b7c1926fe64a86c5279ed187b88c730715880c34a01ec6b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cupy
    - xarray

test:
  # Skip `import` as it requires loading `libcuda.so`, which is not present.
  # imports:
  #   - cupy_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cupy-xarray/
  summary: Interface for using cupy in xarray, providing convenience accessors.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - dcherian
    - jacobtomlinson
    - jakirkham
