{% set name = "cupy-xarray" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3a0793efb90892bb56c7b5cc6d609732ee5d523169dd4925d76c372fffeababc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cupy
    - xarray >=0.19

test:
  # Skip `import` as it requires loading `libcuda.so`, which is not present.
  # imports:
  #   - cupy_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cupy-xarray/
  summary: Interface for using cupy in xarray, providing convenience accessors.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - dcherian
    - jacobtomlinson
    - jakirkham
